Move test for incorrect USE_DROPBOX value to separate test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -64,7 +64,7 @@ if [ -n "$NGINX_VERSION" ] || [ -n "$PHP_VERSION" ] || [ -n "$WORDPRESS_VERSION"
 fi
 
 # Make sure that all dropbox variables have been set.
-if [ -z "$USE_DROPBOX" ] || [ -n "$USE_DROPBOX" ] || [ -z "$DROP_NGINX_URL" ] || [ -z "$DROP_PHP_URL" ]; then
+if [ -z "$USE_DROPBOX" ] || [ -z "$DROP_NGINX_URL" ] || [ -z "$DROP_PHP_URL" ]; then
   echo "Aborting. Environment variables controlling buildpack must have dropbox variables set."
   echo ""
   echo "Change these heroku configs and push again:"
@@ -73,16 +73,6 @@ if [ -z "$USE_DROPBOX" ] || [ -n "$USE_DROPBOX" ] || [ -z "$DROP_NGINX_URL" ] ||
   if [ -z "$USE_DROPBOX" ]; then
     echo "    You must set USE_DROPBOX=true or USE_DROPBOX=false"
 	echo "    heroku config:set   USE_DROPBOX=true"
-  fi
-
-  if [ -n "$USE_DROPBOX" ]; then
-    if [ "$USE_DROPBOX" != "true" ]; then
-      if [ "$USE_DROPBOX" != "false" ]; then
-        echo "    You must set USE_DROPBOX to either true or false!"
-		echo "    Current value for USE_DROPBOX is: $USE_DROPBOX"
-	    echo "    heroku config:set   USE_DROPBOX=true"
-      fi
-	fi
   fi
 
   if [ -z "$DROP_NGINX_URL" ]; then
@@ -100,6 +90,20 @@ if [ -z "$USE_DROPBOX" ] || [ -n "$USE_DROPBOX" ] || [ -z "$DROP_NGINX_URL" ] ||
   fi
 
   exit 250
+fi
+
+# Make sure the USE_DROPBOX variable is set correctly.
+if [ -n "$USE_DROPBOX" ]; then
+  if [ "$USE_DROPBOX" != "true" ]; then
+    if [ "$USE_DROPBOX" != "false" ]; then
+      echo "Aborting. The USE_DROPBOX environment variable must be set correctly."
+      echo ""
+      echo "    You must set USE_DROPBOX to either true or false!"
+	  echo "    Current value for USE_DROPBOX is: $USE_DROPBOX"
+	  echo "    heroku config:set   USE_DROPBOX=true"
+	  exit 250
+    fi
+  fi
 fi
 
 # Support end-user configured BUILDPACK_NGINX_VERSION, BUILDPACK_PHP_VERSION, BUILDPACK_WORDPRESS_VERSION,
